### ISSUE TITLE
 cow 不能正常工作 [Error] An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by graminc** [cyfdecyf/cow#138]
2014/04/28 11:07:52 COW 0.9.1 listen http 127.0.0.1:8080, PAC url http://127.0.0
.1:8080/pac
[DEBUG] 2014/04/28 11:08:08 connPool channel muxConn: cleanup done
[DEBUG] 2014/04/28 11:08:27 cli(127.0.0.1:58408) connected, total 1 clients
[DEBUG] 2014/04/28 11:08:27 cli(127.0.0.1:58408) connPool no conn www.dataxx.com
:80
[DEBUG] 2014/04/28 11:08:29 connected to: www.dataxx.com:80 via shadowsocks: sak
ura.xxxx:3344
[DEBUG] 2014/04/28 11:08:29 cli(127.0.0.1:58408) connected to www.dataxx.com:80
1 concurrent connections
[DEBUG] 2014/04/28 11:08:33 cli(127.0.0.1:58410) connected, total 2 clients
[DEBUG] 2014/04/28 11:08:33 cli(127.0.0.1:58410) connPool no conn online.user.ma
xthon.cn:80
[DEBUG] 2014/04/28 11:08:33 cli(127.0.0.1:58410) connected to online.user.maxtho
n.cn:80 1 concurrent connections
[DEBUG] 2014/04/28 11:08:33 cli(127.0.0.1:58410) request body sent POST online.u
ser.maxthon.cn:80/set
[DEBUG] 2014/04/28 11:08:33 cli(127.0.0.1:58410) connPool put online.user.maxtho
n.cn:80
[DEBUG] 2014/04/28 11:08:33 connPool online.user.maxthon.cn:80: new channel
[DEBUG] 2014/04/28 11:08:48 connPool channel online.user.maxthon.cn:80: close on
e conn
[DEBUG] 2014/04/28 11:08:48 close connection to online.user.maxthon.cn:80 remain
s 0 concurrent connections
[DEBUG] 2014/04/28 11:08:48 connPool channel online.user.maxthon.cn:80: remove
[DEBUG] 2014/04/28 11:08:50 cli(127.0.0.1:58410) parse request read client reque
st timeout
[DEBUG] 2014/04/28 11:08:50 cli(127.0.0.1:58410) closed, total 1 clients
[DEBUG] 2014/04/28 11:08:50 connPool channel online.user.maxthon.cn:80: cleanup
done
[DEBUG] 2014/04/28 11:08:52 read response status line WSARecv tcp 111.14.xxx.xx
:58409: An established connection was aborted by the software in your host machi
ne. GET www.dataxx.com:80/content/date_20140425.html
[DEBUG] 2014/04/28 11:08:52 cli(127.0.0.1:58408) server read error parse respons
e *net.OpError WSARecv tcp 111.14.xxx.xx:58409: An established connection was a
borted by the software in your host machine. GET www.dataxx.com:80/content/date_
20140425.html
[DEBUG] 2014/04/28 11:08:52 close connection to www.dataxx.com:80 remains 0 conc
urrent connections
[DEBUG] 2014/04/28 11:09:09 cli(127.0.0.1:58408) parse request read client reque
st timeout
[DEBUG] 2014/04/28 11:09:09 cli(127.0.0.1:58408) closed, total 0 clients

浏览器页面提示信息:
[Error] WSARecv tcp 111.14.xxx.xx:62301: An established connection was aborted by the software in your host machine.

HTTP Request GET www.tracemyip.org:80/

parse response

Using shadowsocks proxy sakura.xxxx:3344.

Generated by COW 0.9.1 
Host SAMSUNG-PC 
Mon Apr 28 11:51:12 2014

**Comment by ayooay** [comment]
这个页面错误的提示，可以不打印出来或者更改吗。是配置的还是写代码里面的  @cyfdecyf
