### ISSUE TITLE
可以编译一个mips的版本吗？

### ISSUE THREAD

**Issue by aloasut** [cyfdecyf/cow#139]
今天帮人装了一个Netgear R6300V2的，cow支持arm，帅呆了。
回家想折腾自己的R6300V1，发现是mips的，晕倒了。
system type             : Broadcom BCM5300 chip rev 1
processor               : 0
cpu model               : MIPS 74Kc V4.9

翻看了lz以前的帖子，说mips内存小。现在v1和v2都是256M内存的，应该可以吧？

**Comment by victorshell** [comment]
拿去吧 [https://github.com/victorshell/CowAR71xx]
