### ISSUE TITLE
[建议]能否修改或者增加ssh连接方式使用sshpass命令或者其他基于用户密码认证方式的方案？

### ISSUE THREAD

**Issue by jzp820927** [cyfdecyf/cow#141]
作者限制的 ssh public key authentication 认证方式，除非是自己有VPS的情况，才行，而对于普通用户而言，基本上是使用别人分享的SSH资源，而分享的SSH基本上全部都是基于用户密码的认证方式，所以从实际使用情况来说，基于普通的户名密码认证方式应该是占所有SSH使用者80%以上，所以作者的ssh连接功能实际可使用范围就相当小了，所以在此诚恳的建议作者，可否考虑修改，或者增加通过 sshpass 或者 expect (我目前所知的基于用户密码认证的自动化方案就这2种) 来进行ssh连接，sshpass可以通过把密码作为命令参数传递给命令来进行ssh连接，使用比较简单。或者作者有其他更好的用户密码认证自动化方案也行。如果作者不想修改，或者没有时间修改，也请能否详细说明一下应该修改源代码哪个文件的哪段代码，可以实现，本人对GO语言没有任何基础，只会BASH SHELL脚本。总之就是希望作者能增加基于普通用户密码认证方式的SSH连接，非常感谢。

**Comment by HeGanjie** [comment]
遇到同样的问题，我的解决方案：
.ssh/config
```
Host cow-hack
	ProxyCommand sshpass -p <your-pass-word> ssh -NT -D %p %r

# machine which need password
Host nickName1
	HostName <real-host>
	User <user-name>
```

.cow/rc
```
sshServer = nickName1@cow-hack:7000:7000
```
