### ISSUE TITLE
关于 OpenWrt 支持

### ISSUE THREAD

**Issue by JmPotato** [cyfdecyf/cow#154]
现阶段的 Linux 版本能跑在 OpenWrt 上吗？如果不能是否考虑添加支持？

**Comment by nsznsznsz** [comment]
我折腾了一个星期 编译出了一个gccgo 然后可以编译成mipsel的程序 放在我的极路由上运行 但是运行了一会就会崩溃 初步检查的结果发现的go的垃圾回收有问题 内存不足 崩了
