### ISSUE TITLE
公司上外网必须要设置代理，如何使cow通过公司代理服务器连接？

### ISSUE THREAD

**Issue by AndyWing** [cyfdecyf/cow#224]
公司上外网必须要设置代理（8080端口，别的一些端口都无法通过此代理连接，如ssh之类，问过上面说是需要防火墙申请才行）
目前使用goagent可以不用设置公司代理可以上，我如何做才能使Cow能连接到我的shadowsocks服务器（比如29333）？
能不能帮忙下，谢谢啦

**Comment by whiteskin** [comment]
install proxifier, which enable software to use a proxy to connect internet without proxy setting.

add your company proxy in proxifier

add a rule in proxifier, enable cow.exe to use your company proxy

set your proxy in your browser, like default one,127.0.0.1 port 7777


done


I do hope a function of secondary proxy setting like this can be added in future
