### ISSUE TITLE
stat.txt初具规模之前太痛苦，能否来个基本能用的？

### ISSUE THREAD

**Issue by gonejack** [cyfdecyf/cow#252]
不提供一个基本的stat.txt的话，要用不少时间去生成，这过程很麻烦，五六秒的检测时间太慢了。

cow 对 youtube 的支持很惨，xxx.googlevideo.com 这样的每一条地址都要检测一下，这样一来，几乎每看一个视频都要等几秒钟，才会加载视频，能否改进一下。

另外~/.cow/blocked 在windows里是不是blocked.txt，readme里并未提及。

cow能不能只让http数据走goagent，其它走shadowsocks，希望cow能自带goagent实现，goagent原生那客户端导入证书，pac可被外部访问导致本地文件能被遍历，个人对goagent的安全性非常怀疑，只能放弃。

**Comment by bitweng** [comment]
同感，检测方式还不够智能
