### ISSUE TITLE
请问pac文件在哪?

### ISSUE THREAD

**Issue by xwj1003** [cyfdecyf/cow#262]
我想修改一下

**Comment by xwj1003** [comment]
比如我有2个代理 ssh1, ssh2.
如果让某一个域名只能通过 ssh2 通过呢. 最好支持通配符 例如: *.*amazon*.com

**Comment by bombless** [comment]
PAC 是动态生成的，不是一个文件。参考 pac.go 文件里的 genPAC 函数：
https://github.com/cyfdecyf/cow/blob/97d7925a0e9a2550669f4be67b1f08ec59f203a0/pac.go#L144

**Comment by bombless** [comment]
参考文档的“手动指定被墙和直连网站”一节，无法分别指定被墙的网站： [手动指定被墙和直连网站](https://github.com/cyfdecyf/cow/tree/97d7925a0e9a2550669f4be67b1f08ec59f203a0#user-content-%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9A%E8%A2%AB%E5%A2%99%E5%92%8C%E7%9B%B4%E8%BF%9E%E7%BD%91%E7%AB%99)

**Comment by xwj1003** [comment]
请问一下~/.cow/这个是安装目录吗?

**Comment by xwj1003** [comment]
我刚做了一个测试, 在安装目录新建一个文件blocked,里面就一行:myipaddress.com
测试发现没有走代理啊。何解?

**Comment by bombless** [comment]
可以在文件浏览器中输入`%USERPROFILE%\.cow`打开这个目录

**Comment by cyfdecyf** [comment]
@xwj1003 blocked 文件添加记录之后要重启 cow 才能生效。

**Comment by xwj1003** [comment]
按照上面的步骤测试无效.
%USERPROFILE%\.cow\blocked
里面就一行  myipaddress.com
关闭再打开cow-taskbar.exe
myipaddress.com 显示的不是代理的IP, 而是国内IP.
--
建议目录改成安装目录, 因为放在%USERPROFILE%\.cow,很容易因为重装系统而丢失.

**Comment by wogong** [comment]
@xwj1003 `~/.cow/blocked` 对应 Windows 下的安装目录中的 blocked.txt.
