### ISSUE TITLE
是否也能像GA那样能在cmd里显示调试信息

### ISSUE THREAD

**Issue by morefreeze** [cyfdecyf/cow#264]
加个debug参数啥的，能看到哪些用了什么代理？

**Comment by dofine** [comment]
同问，在 Linux 上用命令行参数是可以看到的，但是 Windows 上加了 `-debug -request` 参数也是什么输出都没有。

**Comment by cyfdecyf** [comment]
调试信息的选项可以通过 `cow -h` 看到。

@dofine 可能是 rc 文件里指定了 `logFile`。
