### ISSUE TITLE
能否编译到openwrt/tomato上使用？

### ISSUE THREAD

**Issue by ffox** [cyfdecyf/cow#267]
如果能在路由器上用就太方便了！

**Comment by Veelian** [comment]
同样期待啊！用ChinaDNA怎么配都是全翻啊。

**Comment by dansean** [comment]
自己编译上传到路由器上不就可以了！

**Comment by zx9597446** [comment]
golang cross compile到MIPS现在还不是一件容易的事情
希望1.5能解决， 有编译成功的可以共享下

**Comment by dansean** [comment]
1.5? TMD,我Ubuntu 上還是1.3……
