### ISSUE TITLE
Windows 版本报错，不知道是什么问题？

### ISSUE THREAD

**Issue by jzp820927** [cyfdecyf/cow#271]
从 http://dl.chenyufei.info/cow/ 下载的编译好的 Windows 版本，然后报如下错误：
create shadowsocks cipher: Unsupported encryption method: RC4-MD5
create shadowsocks cipher: Unsupported encryption method: AES-256-CFB
是不是少了什么组件，好像在 Windows 下不支持 shadowsocks 二级代理？

**Comment by Aivier** [comment]
加密方式必须全部小写

**Comment by jzp820927** [comment]
原来是大小写敏感滴，谢谢！
