### ISSUE TITLE
建议在 hash 模式下增加代理连接速度检测

### ISSUE THREAD

**Issue by Jamesits** [cyfdecyf/cow#275]
目前几十个代理 hash，有几个代理速度很慢或者连接不上，会导致部分网站访问极其缓慢。是否能对每个代理的连接速度进行检测，如果速度过低则暂时不使用？

**Comment by cyfdecyf** [comment]
配置文件里用 `loadBalance = latency`。

**Comment by Jamesits** [comment]
这样就只能选择一个了。有些代理前面有一层国内服务器，或者本机有其他软件做的 HTTP 代理的话响应速度会异常快，导致测速实质上失效。
