### ISSUE TITLE
Line和facebook上不去 有办法解决么

### ISSUE THREAD

**Issue by Ehekatl** [cyfdecyf/cow#282]
据说是因为用的spdy协议
现在http/2都出来了
什么时候能增加支持么
还是http代理的天然bug 没法解决？

**Comment by cyfdecyf** [comment]
SPDY 本身可以使用支持 HTTPS 协议的代理，不能用是由于有些 app 不理会代理设置。详情可以参考 [v2ex 上的讨论](http://www.v2ex.com/t/77221)。
