### ISSUE TITLE
负载均衡加入随机模式

### ISSUE THREAD

**Issue by sunshineplan** [cyfdecyf/cow#285]
hash模式每次出现的结果都是一样的
latency模式每次测速间隔也很短，是否可以加入自定义时间
是不是可以添加一种随机模式，更加提高效率。

**Comment by sunshineplan** [comment]
另外latency模式测速时，如果ss服务器是ip填的话，并不在测速列表里面，不知道这个算不算bug。
以及错别字一枚“lantency lowest proxy”

**Comment by cyfdecyf** [comment]
随机到哪个 server 是通过请求的 host name 来决定的，特意这样设计的原因是有些网站对登录 session 要求使用同一个 IP，否则会终端 session。典型的例子是 https://appleid.apple.com，曾经被坑过。

**Comment by sunshineplan** [comment]
的确，目前我测下来，如果频繁的更换ip的话，会有其他问题伴随，特别是安全性比较高的网站会中止会话。所以随机并不是一个好办法。
