### ISSUE TITLE
访问百度经常被reset是什么情况？

### ISSUE THREAD

**Issue by louis-sherren** [cyfdecyf/cow#286]
我是aws上起了shadowsocks服务，本机起cow，然后chrome用switchy插件来做HTTP代理
不过在访问百度还有其他网站时经常被reset（一般是第一次访问被reset），百度属于国内网站，cow应该不会将请求发送到aws吧

**Comment by cyfdecyf** [comment]
百度不会通过二级代理访问，不确定是不是由于 cow 经常通过连接百度来判断网络状态导致被 reset 的。

试试看启动 cow 时加上 `-estimate=false` 选项，看下还有没有这个问题。

**Comment by ddatsh** [comment]
另，看了下代码，貌似 RC 配置里没有设置estimate的吧？
