### ISSUE TITLE
cow把shadowsocks的socks5转成http，但是却遇到dns污染的问题。

### ISSUE THREAD

**Issue by cloudop** [cyfdecyf/cow#287]
我在同一台服务器上同时安装了cow和shadowsocks，这台服务器在新加坡。
用cow把shadowsocks的socks5转成http（想要提供给手机的apn用）。
访问twitter就会出现dns污染现象，如果是直接使用socks5就不会。
请大家给个建议，这是为什么呢？

**Comment by cyfdecyf** [comment]
是通过 twitter 客户端访问的时候遇到这个问题么？直接用浏览期有没有问题？

一个可能的原因是 twitter 客户端自己做 DNS 解析，然后再发送请求给 cow。如果直接把访问 twitter 的请求发给 cow 会直接使用二级代理来访问。

**Comment by cloudop** [comment]
不是通过客户端，是通过浏览器。
我把cow安装到国内之后，twitter就不会被dns污染了。国内cow与国外shadowsocks之间通信是加密的。
我初步判断是通往国外的流量是被GFW监控的，而走国内的流量则没有，或者不严格。
还有一种办法是把pac文件的地址由http改成https，敏感域名也可以不被GFW检测到而被污染。

**Comment by cyfdecyf** [comment]
之前没看仔细，client 和 cow 通信没有加密，如果 cow 安装在国外是会收到干扰。
