### ISSUE TITLE
OS X下如何完整删除cow（安装为默认地址，即~/.）？

### ISSUE THREAD

**Issue by meritozh** [cyfdecyf/cow#288]
是否仅有cow、rc和plist三个文件？安装时有没有残留什么的？

**Comment by pi1ot** [comment]
~/.cow 文件夹

**Comment by meritozh** [comment]
@pi1ot rc文件即在.cow内。我想知道仅仅删除这三个文件就行了吗？

**Comment by pi1ot** [comment]
我这个文件夹就不止这些文件，至少还有stat吧，删除文件夹应该是彻底的办法

**Comment by meritozh** [comment]
@pi1ot 了解，谢谢了

**Comment by cyfdecyf** [comment]
删掉 cow 的二进制文件，再删除 ~/.cow 目录即可。
