### ISSUE TITLE
关于在dd wrt下运行cow的问题

### ISSUE THREAD

**Issue by itcbx** [cyfdecyf/cow#289]
我自行编译了在r7000系统为dd wrt的cow，可是dd-wrt系统有个问题，其用户目录是在/tmp/root下的，这个目录一重启数据就没了，虽然cow的配置文件可以在启动时通过-rc指定位置，可是像诸如~/.cow/stat，~/.cow/blocked 和 ~/.cow/direct这些文件就没办法保存了，不知有什么办法可以改变cow存储文件的位置？比如将整个.cow文件移动到可存储的地方

**Comment by cyfdecyf** [comment]
用脚本来启动和退出 cow 吧，退出后保存，启动前恢复。

**Comment by itcbx** [comment]
目前我的解决方法是，用脚本，先将环境变量HOME临时改变为其他值，然后再启动cow，目前正常运行，应该没问题吧？我看源码貌似就用了这个环境亦是
