### ISSUE TITLE
如何修改pac文件？pac的代理指向的服务器是内网地址啊？

### ISSUE THREAD

**Issue by uuair** [cyfdecyf/cow#291]
问题又来了，cow生成的pac文件，服务器地址指向的是内网地址，而这个pac文件我是在公网上用的。。。怎么修改这个服务器地址啊？

**Comment by uuair** [comment]
我尝试在a服务器上运行cow协议，将listen写成:  
    listen cow://aes-1280cfb:password@0.0.0.0:8888    

但问题是，b电脑还是无法访问到端口，a电脑却可以使用telnet访问到。我怀疑是安装软件的问题？
但如何删除电脑上的cow啊？我使用的是说明中的curl -L的方法安装的。

**Comment by cyfdecyf** [comment]
配置文件[注释](https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc#L20)有说明。
