### ISSUE TITLE
10.10.2 ，系统设置 pac 时，会导致 airdrop 不可用

### ISSUE THREAD

**Issue by Visoar** [cyfdecyf/cow#292]
![image](https://cloud.githubusercontent.com/assets/2937078/6520605/eedbae92-c403-11e4-886e-d61bbdc1f392.png)

**Comment by uuair** [comment]
你的cow，部署到了yosemite系统上了，所以用的地址是127的对么？

**Comment by Visoar** [comment]
对的，配置情况如图所示 https://cloud.githubusercontent.com/assets/2937078/6520605/eedbae92-c403-11e4-886e-d61bbdc1f392.png

**Comment by WilliamZhang515** [comment]
是的，我也不可用

**Comment by Visoar** [comment]
10.10.3 这个问题仍然存在

**Comment by Visoar** [comment]
是否可以在 pac 文件里加入

if (shExpMatch(url, "*.local"))
    return "DIRECT";

来避免这个问题呢？

**Comment by cyfdecyf** [comment]
试了一下，的确关掉代理配置之后就可以从 Mac 上通过 AirDrop 发现 iPhone 了。能给个原因的说明么？

**Comment by cyfdecyf** [comment]
develop branch 已经修复。找时间把 binary 的发布通过 gobuild 来完成，现在发布 binary 的方式太麻烦了。

**Comment by Visoar** [comment]
目前是否有已发布了的修复了这个问题的版本？还说是如果要用修复后的版本，需要自行把 develop branch 的代码 git 下来编译呢？

**Comment by cyfdecyf** [comment]
@Visoar 下周会发布新版。

**Comment by cyfdecyf** [comment]
已经发布 0.9.5。
