### ISSUE TITLE
使用pac无法连接https的网站，同时无法使用当前电脑的网络访问互联网。

### ISSUE THREAD

**Issue by uuair** [cyfdecyf/cow#293]
我使用了pac访问互联网，cow安装到了公网上。可是，无法访问https的网站，除非我在safari的https代理上也写上cow的地址。可如果是iphone，只能选择使用pac，那么怎么办？

如果使用了pac代理，墙外走一个线路，墙内的流量都走cow这台服务器了，有没有办法走我本机的线路呢？我使用pac的时候访问ip138，都是显示的cow这个地址，而不是我自己使用当前网络的地址。

**Comment by cyfdecyf** [comment]
在 OS X 上 https 协议的代理的确要另外指定的。iPhone 上能正常使用 PAC。

第二个问题在 direct 文件里指定本地的某几台常用机器 ip 来解决吧。
