### ISSUE TITLE
stat 文件为什么每次删除？

### ISSUE THREAD

**Issue by ferocknew** [cyfdecyf/cow#295]
有多台机器，可以互相学习，用ln -s 的软连接就可以做到备份并同步。
但是每次删除，软连接就会失效，结果还是每次都要重新学习。

这个易用性不太好。

**Comment by cyfdecyf** [comment]
cow 保存 stat 文件的步骤：

```
# create new stat.tmp
rm stat.bak
mv stat stat.bak
mv stat.tmp stat
```

软链接只会临时失效一下。

多台机器同步有个问题，需要合并直连网站列表。
