### ISSUE TITLE
增加一个简单的「直连」与「翻墙」列表管理界面

### ISSUE THREAD

**Issue by glacjay** [cyfdecyf/cow#296]
好吧我反悔了，自动检测是否被墙的机制并不总是能工作良好，一定的手动微调能力还是有必要的 :-)

以前强调自动化，一是因为自动化确实使用比较方便，二则是因为手动控制的话就意味着手工修改配置文件然后重启 COW 进程，不是很方便。现在有了统计持久化功能，在此基础上就可以考虑增加一个简单的微调配置界面了。

目前想到的设计思路如下：直接访问 http://localhost:7777（COW 监听端口）时，显示一个列表，每一项对应最近访问过的一个域名，每个域名支持三个操作：「直连」、「翻墙」和「自动」，分别对应于对该域名的 `VisitCnt` 值的修改：「直连」将 `Direct` 置为 `-1`；「翻墙」将 `Blocked` 置为 `-1`；「自动」则将两者均重置为 `0`（如果之前是 `-1` 的话）。不知道该思路是否可行呢。

如果啥时有心情的话我会试着实现一下的 :-)

**Comment by aoxu** [comment]
GoAgentX就是cow的GUI，支持你说的功能。

在 2015年3月14日 上午1:19，GlacJAY <notifications@github.com>写道：

> 好吧我反悔了，自动检测是否被墙的机制并不总是能工作良好，一定的手动微调能力还是有必要的 :-)
>
> 以前强调自动化，一是因为自动化确实使用比较方便，二则是因为手动控制的话就意味着手工修改配置文件然后重启 COW
> 进程，不是很方便。现在有了统计持久化功能，在此基础上就可以考虑增加一个简单的微调配置界面了。
>
> 目前想到的设计思路如下：直接访问 http://localhost:7777（COW
> 监听端口）时，显示一个列表，每一项对应最近访问过的一个域名，每个域名支持三个操作：「直连」、「翻墙」和「自动」，分别对应于对该域名的
> VisitCnt 值的修改：「直连」将 Direct 置为 -1；「翻墙」将 Blocked 置为 -1；「自动」则将两者均重置为 0（如果之前是
> -1 的话）。不知道该思路是否可行呢。
>
> 如果啥时有心情的话我会试着实现一下的 :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyfdecyf/cow/issues/296>.
>



-- 
-------------------------------------------------------
XA
blog: aoxuis.me

**Comment by glacjay** [comment]
@aoxu 但我同时也是 Windows 用户肿么破？

**Comment by aoxu** [comment]
原来如此。。。

GlacJAY <notifications@github.com>于2015年3月14日星期六写道：

> @aoxu <https://github.com/aoxu> 但我同时也是 Windows 用户肿么破？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyfdecyf/cow/issues/296#issuecomment-79787970>.
>


-- 
-------------------------------------------------------
XA
blog: aoxuis.me

**Comment by lbp0200** [comment]
直接用pac文件来管理吧，兼容性好

**Comment by glacjay** [comment]
@lbp0200 那 PAC 文件要怎么管？不要告诉我用 COW 管，这不就又绕回去了？

**Comment by lbp0200** [comment]
@glacjay 
1、pac文件可以做成配置文件，安装自带，需要使用者自行下载更新。我现在用这个pac文件，https://github.com/Leask/Flora_Pac，非常好用，根据权威ip数据，生成pac，国内直连，国外代理。
2、我现在经常遇到的问题就是在linux上，很多软件需要在线安装，比如ruby的rvm，php的composer，apt更新，有需要连到国内，也有国外，连国外不用代理只有几K的速度，还不能用pac，浏览器就没这种烦恼。
3、我看了下cow源码，发现在代码里有一个变量保存了pac文件内容，但是我不确定这个变量的作用。
