### ISSUE TITLE
Trojan.Gen

### ISSUE THREAD

**Issue by sandylaw** [cyfdecyf/cow#298]
![诺顿查出了病毒](http://ww1.sinaimg.cn/large/4cfe3a92jw1eq795lj3akj20f80cfdj7.jpg)

**Comment by ddatsh** [comment]
又一个应该直接 close 的issue

**Comment by sandylaw** [comment]
为什么这么说？
企业用的诺顿，虽然我已经把cow文件夹添加到扫描排除项了，但还是会是不是被杀毒删掉cow.exe文件。

**Comment by ddatsh** [comment]
心理安慰产品多年没有用过了
