### ISSUE TITLE
是否有计划增加【多用户流量限制】类似的功能？

### ISSUE THREAD

**Issue by timchou** [cyfdecyf/cow#300]
Hi

我是个小白

最近在配合使用cow + shadowsocks搭建服务，提供pac文件，给iOS用户在WiFi下基本的翻墙。

但是发现使用了pac文件就无法进行用户认证了，也就是说用户只要拿到了pac文件，就能无限制的使用了。

后来我发现在WiFi下，http代理改为手动，就可以进行用户认证，IP,PORT,USERNAME,PASSWORD，可以配合COW的rc文件中的userPasswdFile这个参数来进行基本的用户认证。

但这样还是无法统计用户的流量。

所以我的想请问，后续是否有计划会增强用户认证这块？

ps，小白还有个问题：像https://github.com/mengskysama/shadowsocks/tree/manyuser 这样的shadowsocks分支，提供了多用户的功能，并且还能限制流量，很好的满足了我的需求。但是shadowsocks仅提供了SOCKS5代理，没有HTTP代理，因此在iOS下WiFi设置中，没法提供PAC文件或者HTTP代理把？必须要通过类似COW这样的软件来将SOCKS5代理转为HTTP代理。是这样吗？

**Comment by cyfdecyf** [comment]
有 PAC 依然可以认证，只是必须自己手动输入密码。

可以用 [polipo](http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/) 把 socks5 转成 http。
