### ISSUE TITLE
hash功能的疑问

### ISSUE THREAD

**Issue by sunshineplan** [cyfdecyf/cow#302]
我有4个代理，使用的是hash做负载均衡，结果发现0-3这四个代理中，2号被hash中的概率高的离谱，3号没有被hash中过，以下是hash的结果：
hash host 23.21.235.223 try 0 parent first
hash host bits.wikimedia.org try 0 parent first
hash host en.wikipedia.org try 0 parent first
hash host zh.wikipedia.org try 0 parent first
hash host 213.174.129.180 try 1 parent first
hash host www.vpngate.net try 1 parent first
hash host 0.client-channel.google.com try 2 parent first
hash host 0.docs.google.com try 2 parent first
hash host 108.170.1.21 try 2 parent first
hash host 2.client-channel.google.com try 2 parent first
hash host 3.client-channel.google.com try 2 parent first
hash host 4.client-channel.google.com try 2 parent first
hash host abs.twimg.com try 2 parent first
hash host accounts.google.com try 2 parent first
hash host ajax.googleapis.com try 2 parent first
hash host android.clients.google.com try 2 parent first
hash host api.facebook.com try 2 parent first
hash host api.twitter.com try 2 parent first
hash host api0.dropbox.com try 2 parent first
hash host api-d.dropbox.com try 2 parent first
hash host apis.google.com try 2 parent first
hash host autoproxy-gfwlist.googlecode.com try 2 parent first
hash host b-api.facebook.com try 2 parent first
hash host b-graph.facebook.com try 2 parent first
hash host calendar.google.com try 2 parent first
hash host client.dropbox.com try 2 parent first
hash host client-lb.dropbox.com try 2 parent first
hash host clients2.google.com try 2 parent first
hash host clients3.google.com try 2 parent first
hash host clients4.google.com try 2 parent first
hash host clients5.google.com try 2 parent first
hash host clients6.google.com try 2 parent first
hash host content.googleapis.com try 2 parent first
hash host docs.google.com try 2 parent first
hash host drive.google.com try 2 parent first
hash host ds.ssw.live.com try 2 parent first
hash host feedly.com try 2 parent first
hash host fonts.googleapis.com try 2 parent first
hash host gdata.youtube.com try 2 parent first
hash host gg.google.com try 2 parent first
hash host google.com try 2 parent first
hash host graph.facebook.com try 2 parent first
hash host i.ytimg.com try 2 parent first
hash host id.google.com try 2 parent first
hash host img.feedly.com try 2 parent first
hash host inbox.google.com try 2 parent first
hash host lh3.ggpht.com try 2 parent first
hash host lh3.google.com try 2 parent first
hash host lh3.googleusercontent.com try 2 parent first
hash host lh4.google.com try 2 parent first
hash host lh4.googleusercontent.com try 2 parent first
hash host lh5.google.com try 2 parent first
hash host lh5.googleusercontent.com try 2 parent first
hash host lh6.ggpht.com try 2 parent first
hash host lh6.google.com try 2 parent first
hash host lh6.googleusercontent.com try 2 parent first
hash host mail.google.com try 2 parent first
hash host mail-attachment.googleusercontent.com try 2 parent first
hash host maps.gstatic.com try 2 parent first
hash host mobile.twitter.com try 2 parent first
hash host mt0.google.com try 2 parent first
hash host mtalk.google.com try 2 parent first
hash host notify9.dropbox.com try 2 parent first
hash host oauth.googleusercontent.com try 2 parent first
hash host oc.umeng.com try 2 parent first
hash host onlineadv.goforandroid.com try 2 parent first
hash host pbs.twimg.com try 2 parent first
hash host pki.google.com try 2 parent first
hash host play.google.com try 2 parent first
hash host plus.google.com try 2 parent first
hash host plusone.google.com try 2 parent first
hash host s3.feedly.com try 2 parent first
hash host safebrowsing.google.com try 2 parent first
hash host ssl.google-analytics.com try 2 parent first
hash host ssl.gstatic.com try 2 parent first
hash host talkgadget.google.com try 2 parent first
hash host tools.google.com try 2 parent first
hash host translate.google.com try 2 parent first
hash host twitter.com try 2 parent first
hash host www.dropbox.com try 2 parent first
hash host www.google.com try 2 parent first
hash host www.google-analytics.com try 2 parent first
hash host www.googleapis.com try 2 parent first
hash host www.gstatic.com try 2 parent first
hash host www.youtube.com try 2 parent first
hash host www.youtube-nocookie.com try 2 parent first
hash host www-gm-opensocial.googleusercontent.com try 2 parent first
hash host www-opensocial.googleusercontent.com try 2 parent first
hash host yt3.ggpht.com try 2 parent first

**Comment by sunshineplan** [comment]
突然发现，.com都是一个结果，.org都是一个结果，.net都是一个结果

**Comment by rjzou** [comment]
你这个在哪里看到的呢?

**Comment by cyfdecyf** [comment]
不错的观察，或许我用的 [djb2 string hash](https://github.com/cyfdecyf/cow/blob/master/util.go#L456) 不太适用作 hostname 的 hash。但实际上不会出现所有的 .com 都是同一个结果的问题，这里有个[例子](https://play.golang.org/p/of5o-H4n6v)。

**Comment by sunshineplan** [comment]
设置结点数不同的时候，的确和最后的域名无关

我找了一个一致性哈斯的方法
https://github.com/studyGo/consistenthash
然后用前面的数据测了一下新方法和原来的方法，结果如下：

新方法结点2		原方法结点2	
a 计数	40		0 计数	80
b 计数	41		1 计数	1
新方法结点3		原方法结点3	
a 计数	33		0 计数	25
b 计数	16		1 计数	25
c 计数	32		2 计数	31
新方法结点4		原方法结点4	
a 计数	16		0 计数	4
b 计数	16		1 计数	1
c 计数	22		2 计数	76
d 计数	27			
新方法结点5		原方法结点5	
a 计数	11		0 计数	9
b 计数	15		1 计数	19
c 计数	22		2 计数	14
d 计数	25		3 计数	19
e 计数	8		4 计数	20
新方法结点6		原方法结点6	
a 计数	9		0 计数	24
b 计数	12		2 计数	31
c 计数	19		3 计数	1
d 计数	25		4 计数	25
e 计数	8			
f 计数	8			
新方法结点7		原方法结点7	
a 计数	9		0 计数	17
b 计数	10		1 计数	8
c 计数	12		2 计数	7
d 计数	22		3 计数	8
e 计数	8		4 计数	18
f 计数	8		5 计数	8
g 计数	12		6 计数	15

某些情况下，原来的方法得出的结果十分极端

**Comment by cyfdecyf** [comment]
Fixed in e23bd65.

对 djb2 和 crc32 做了个[简单的比较](https://github.com/cyfdecyf/hash-test)，dbj2 的 hash 结果分布非常不均匀，crc32 就好很多。Go 的 crc32 实现使用了 Intel SSE 中的 CRC 指令，性能应该不差。
