### ISSUE TITLE
http proxy不好使，卡顿严重

### ISSUE THREAD

**Issue by ncisoft** [cyfdecyf/cow#303]
环境：一个socks5代理，一个privoxy代理socks5，一个cow代理socks5或privoxy

表现：直接用privoxy代理socks5或cow代理socks5都很流畅；但用cow代理privoxy就卡顿严重，尤其看youtube

是否Cow代理http存在问题？

Privoxy可配置多个user defined action，比如不同域名走不同代理，很好用。如果cow能支持，可以节省cow的大量功能。

**Comment by cyfdecyf** [comment]
我很少看视频，cow 在处理视频类网站上可能是存在问题。

我写 cow 就是不想自己定义使用代理的规则。
