### ISSUE TITLE
能不能指定PAC文件中，服务器的IP地址？

### ISSUE THREAD

**Issue by pfitseng** [cyfdecyf/cow#306]
我把COW放在docker容器中，默认的地址是DOCKER的内网地址，导致外网无法访问到，能不能在配置文件中指定生成的服务器地址？

**Comment by slgray** [comment]
同样的问题，希望能改进。

**Comment by cyfdecyf** [comment]
配置文件支持的，看[这里](https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc#L22)。

**Comment by slgray** [comment]
修改了配置文件，可以了，谢！
