### ISSUE TITLE
Error decoding site stat: unexpected end of JSON input

### ISSUE THREAD

**Issue by lawzhangqi** [cyfdecyf/cow#308]
树莓派中安装了COW，几次跑下来后，就这个错误了。
删除stat文件，重新运行无效。有啥办法可以解决。

**Comment by renzhn** [comment]
试试 https://github.com/renzhn/MEOW
我在树莓派2日常使用~

**Comment by fzerorubigd** [comment]
Duplicate of #309 and fixed in #313 , please close this if 313 got merged.

**Comment by ouwenxxing** [comment]
@lawzhangqi 我用的是Raspberry Pi2
系统：Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l

用了2个月cow了，完全没问题。。

**Comment by cyfdecyf** [comment]
Thanks for @fzerorubigd, the problem is fixed in develop branch now.

I'll release a new version very soon, though there'll be no big bug fixes.
