### ISSUE TITLE
Cow starts failure if .cow/stat corrupts

### ISSUE THREAD

**Issue by mine260309** [cyfdecyf/cow#309]
If `.cow/stat` is corrupted, or it becomes an empty file, cow starts failure with below log:

    Error decoding site stat: unexpected end of JSON input

It occurs commonly on RaspberryPi since the power may be cut off unexpectedly, sometimes it cause `.cow/stat` corrupted or empted.

I would suggest to do below if the file is corrupted:
1) Check if `stat.bak` is valid, if yes, copy it to `stat` and start cow;
2) If `stat.bak` is also broken, just delete them and start with a fresh start.

**Comment by cyfdecyf** [comment]
Fixed by @fzerorubigd and code merged in develop branch now.

**Comment by mine260309** [comment]
Thank you for fixing the issue!
One more question, from the change, I see it's load `.bak` file if `stat` fails to load, but will the stat file be recovered after loading `.bak` file? If no, I guess `.bak` file will eventually corrupted and then both files are deleted. It's better to recover `stat` from `.bak`, right?

**Comment by cyfdecyf** [comment]
When saving `stat` file, the recovered content will be used.
