### ISSUE TITLE
代理服务器拒绝连接

### ISSUE THREAD

**Issue by terrason** [cyfdecyf/cow#310]
当我在浏览器中访问 `https://wenyunet-server.xicp.net:8443/svn/cancer/code/service/patientbook` 时，出现代理服务器拒绝连接
但是`https://www.google.com.tw/`却可以

请问是什么原因？ https 协议不能自定义端口么？

注： 这是一个自己搭建的svn服务器，证书是自签名生成的，访问需要用户名和密码。

**Comment by cyfdecyf** [comment]
出于安全角度考虑，只有常用端口允许建立隧道连接，配置里有选项可以绕过。

https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc#L131
