### ISSUE TITLE
Reload config on SIGUSR1

### ISSUE THREAD

**Issue by fzerorubigd** [cyfdecyf/cow#322]
I want to implement a simple reload functionality on SIGUSR1. 
The implementation is not zero down time, I can use something like https://github.com/rcrowley/goagain or https://github.com/zimbatm/socketmaster but its not important for me, and also there is a problem if the new config contain less or more listener inside. (need more code and I want it to be simple) 

The idea is to kill all listener on SIGUSR1, fork a new cow, and kill the current instance.  
@cyfdecyf any note on this?

**Comment by cyfdecyf** [comment]
Thanks for your implementation, I also like to keep things simple.
