### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by fzerorubigd** [cyfdecyf/cow#324]
Sourcegraph is a good place to read and dive in code. please enable it :)
Just go to https://sourcegraph.com/github.com/cyfdecyf/cow

Thank you!

**Comment by cyfdecyf** [comment]
Enabled now :)

I've heard about Sourcegraph before but haven't tried it. It seems really nice at first glance.

**Comment by fzerorubigd** [comment]
Thanks!
