### ISSUE TITLE
/doc/init.d/cow对mac的兼容并不好

### ISSUE THREAD

**Issue by morefreeze** [cyfdecyf/cow#327]
/doc/init.d/cow这个脚本的29行，在check_running函数中，使用/proc/$pid的方式检测是否存在，但在mac中并没有/proc这个目录，建议用ps直接检测，可以将判断proc那行替换成下面：

`ps aux | awk '$2=='$PID'{ got=1; } END{if (!got) exit 2; }' `
`if [[ $? == 0 ]];then`

**Comment by cyfdecyf** [comment]
Mac 不需要使用这个脚本，安装脚本会下载 launchd 配置文件来实现自动启动。
