### ISSUE TITLE
期待android版本客户端，感谢

### ISSUE THREAD

**Issue by rrkelee** [cyfdecyf/cow#330]

**Comment by yinheli** [comment]
因为是 go 程序, 估计你得在内网搭建一个 cow 服务器, 通过 pac 脚本来实现你的手机 fq 需求.

**Comment by cyfdecyf** [comment]
@yinheli 说的是一种办法。

如果想在 android 上运行 cow 的话，Go 现在有对 Android 的支持，理应能编译出 android 的可执行文件。
