### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by sunshineplan** [cyfdecyf/cow#363]
之前我使用2个cow进程，1个连到另外1个，没有问题。
后来我使用3个cow进程，1个连1个再连另外1个后出现了日志内有乱码的报错，之前cow用的aes-128-cfb加密做二级代理，后用的aes-256-cfb都还是有这个问题。不过感觉不影响使用。

日志如下：
[ERROR] 2015/07/24 14:49:07 split header malformed header: "Y\x89\x14丝\b\x1c\xa9h\x1c-\x1e\x14\xd8\xe0\fmtZK\xa6\xa0com\r\n"
line: Y?丝﹉-剜mtZKcom
raw header:
[ERROR] 2015/07/24 14:49:07 parse request header: malformed header: "Y\x89\x14丝\b\x1c\xa9h\x1c-\x1e\x14\xd8\xe0\fmtZK\xa6\xa0com\r\n" CONNECT clients6.google.com:443

**Comment by sunshineplan** [comment]
另外还有这些
[ERROR] 2015/07/25 08:24:56 can't connect to shadowsocks parent 10.1.66.201:53347 for H赓Y?2n镠ost:: shadowsocks: invalid port H赓Y?2n镠ost:
[ERROR] 2015/07/26 07:12:31 can't connect to shadowsocks parent 10.1.66.201:53347 for !O碾wr-Agent:: shadowsocks: invalid port !O碾wr-Agent:

**Comment by Cumin** [comment]
有时候我在日志也会看到类似的乱码。

**Comment by wufengwhu** [comment]
这个问题解决了吗？我也遇到了
