### ISSUE TITLE
不支持WebSocket 连接~

### ISSUE THREAD

**Issue by aoxu** [cyfdecyf/cow#365]
发现这个问题是在用 https://tower.im/ 的时候，浏览器是Chrome，发现开了桌面通知，实际上却没生效。后来排查了一下，发现有如下错误日志：

```
WebSocket connection to 'wss://pusher.tower.im:8082/app/bb025b016f19e1824544289f1246f0b1?protocol=7&client=js&version=2.2.3&flash=false' failed: Establishing a tunnel via proxy server failed.
```

看来是WebSocket连接被cow拒绝了，我把tower.im域名放进direct走直连也不行，因为在系统层面还是通过cow代理的。

**Comment by paicha** [comment]
通过代理脚本的话，tower.im 应该会直接连接而不走 cow 才对呀。

**Comment by aoxu** [comment]
@paicha 我用的HTTP代理方式，不是PAC方式，因为前者才能自动学习。

**Comment by icefairy** [comment]
@aoxu pac可以自动学习啊

**Comment by aoxu** [comment]
@icefairy 请自己看Readme里PAC和HTTP代理的区别。

**Comment by wwgc** [comment]
想问下这个问题有解决办法没有？

**Comment by jinuljt** [comment]
使用juypter遇到相同的问题。wireshark抓包 jupyter 与 cow两者的数据。发现jupyter没有收到连接，判断应该是cow直接返回了，查看了cow源码，在 proxy.go 中找到下面这段代码。

```
		if r.isConnect && !config.TunnelAllowedPort[r.URL.Port] {
			sendErrorPage(c, statusForbidden, "Forbidden tunnel port",
				genErrMsg(&r, nil, "Please contact proxy admin."))
			return
		}
```

修改cow配置文件，增加8888到tunnelAllowedPort 中。
```
tunnelAllowedPort = 8888
```
