### ISSUE TITLE
kernel_task翻墙

### ISSUE THREAD

**Issue by nickyfoto** [cyfdecyf/cow#369]
kernel_task无法用cow翻墙是吧，shadowsocks可以让kernel_task翻墙吗？

**Comment by pi1ot** [comment]
你有什么需求会需要让kernel_task翻墙？

**Comment by nickyfoto** [comment]
terminal 翻不出去啊

**Comment by pi1ot** [comment]
你应该是想让某个命令行工具翻墙吧，看一下proxychains4
