### ISSUE TITLE
安装遇上问题

### ISSUE THREAD

**Issue by HoshinoTouko** [cyfdecyf/cow#376]
使用
    curl -L git.io/cow | bash
报错
    Unknown SSL protocol error in connection to raw.githubusercontent.com:443
环境raspbian

**Comment by helinb** [comment]
添加 hosts文件
# Github_hosts start
199.27.74.133    assets-cdn.github.com
199.27.78.133    avatars1.githubusercontent.com
199.27.78.133    avatars2.githubusercontent.com
199.27.78.133    avatars3.githubusercontent.com
199.27.74.133    avatars4.githubusercontent.com
199.27.74.133    avatars5.githubusercontent.com
199.27.75.133    avatars6.githubusercontent.com
199.27.74.133    avatars7.githubusercontent.com
199.27.75.133    avatars8.githubusercontent.com
199.27.74.133    camo.githubusercontent.com
199.27.74.133    collector-cdn.github.com
199.27.74.133    documentcloud.github.com
54.243.192.65    enterprise.github.com
192.30.252.142    gist.github.com
199.27.74.133    gist-assets.github.com
192.30.252.128    github.com
103.245.222.249    github.global.ssl.fastly.net
199.27.74.133    goagent.github.io
199.27.74.133    google.github.io
199.27.74.133    help.github.com
192.30.252.147    nodeload.github.com
199.27.74.133    pages.github.com
199.27.74.133    raw.github.com
192.30.252.128    www.github.com
199.27.79.133    huhamhire.github.com
# Github_hosts end

**Comment by HoshinoTouko** [comment]
感谢楼上
