### ISSUE TITLE
试用了下发现ftp不能

### ISSUE THREAD

**Issue by ghostry** [cyfdecyf/cow#378]
curl -L git.io/cow | bash
这样安装的.
然后在ubuntu(1404.3amd64)系统配置里设置http全局代理.
浏览器正常.就发现我的ftp(netbeans)上传不了文件了.有时候提示链接不上,有时候能登陆但是上传不了.
取消全局代理则正常.
不知道是个例还是通病
cow运行界面无提示.

**Comment by billryan** [comment]
建议好好补下计算机网络基础，FTP 和 HTTP 是平级的协议，cow 是一个 HTTP proxy, 而不是 FTP proxy.
要 FTP 的代理需要使用 socks, 而不是 cow

**Comment by rampageX** [comment]
netbeans 不知道，Windows 下 flashfxp 设置 http connect 代理 为 cow 时 OK

**Comment by ghostry** [comment]
oh my god ! 隔了这么久突然有回复了。已经更新好几次了。现在没有这个问题了。
