### ISSUE TITLE
下载最新 Windows 版,出现 only one usage of each socket address 异常

### ISSUE THREAD

**Issue by wenerme** [cyfdecyf/cow#389]
OS WIndows 10
下载的文件为 http://dl.chenyufei.info/cow/latest/cow-win64-0.9.6.zip

相同的配置文件在 Mac OS X 下是可用的

**Comment by Lrevor** [comment]
端口被占用了，要么关掉占用端口的程序，要么就重启电脑吧

**Comment by wenerme** [comment]
应该是的.
