### ISSUE TITLE
请问cow有没有考虑dns污染的问题？

### ISSUE THREAD

**Issue by gjj2828** [cyfdecyf/cow#390]
请问cow有没有考虑dns污染的问题？

**Comment by cyfdecyf** [comment]
DNS 解析在代理服务器完成，只要浏览器不在本地解析即可。

**Comment by gjj2828** [comment]
谢谢，了解了！

**Comment by mawenjian** [comment]
@cyfdecyf 我的cow服务用的是国内服务器，访问Google、Facebook等网站会通过海外的SS服务器做中转。请问在访问Google、Facebook等网站的时候，DNS解析的工作是由cow所在的国内服务器完成的、还是由SS所在的海外服务器完成的呢？
我现在搭建的cow服务，发现访问Google、Gmail这种没被DNS污染的网站是没有问题的，但是访问FB、Twitter这种被DNS污染的就不行（浏览器直接挂SS可以），所以我猜测DNS解析是由国内服务器进行的。
如果我猜测有误的话，那么问题会出在哪里？如果猜测正确，可否有解决方案？谢谢！
