### ISSUE TITLE
osx设置的系统代理pac总是被自动清空

### ISSUE THREAD

**Issue by cikichen** [cyfdecyf/cow#393]
请教下，每次启动shadowsocksX，我的系统代理配置总是会被自动清空，并且处于非勾选状态，老是需要手动去重新设置。

![](http://ww1.sinaimg.cn/large/62b0904dgw1ey8l6a6gg2j20i30e2jsk.jpg)

**Comment by alexwhen** [comment]
alfred,然后用proxy switcher
