### ISSUE TITLE
請問blocked文件格式是什麼

### ISSUE THREAD

**Issue by ShinoharaYuri** [cyfdecyf/cow#398]
twseo.org
單獨的話 IP地址會變變成二級代理的地址

但是如果是
twseo.org
ip.cn
ip138.com
這樣的話三個網站檢測出來IP是原本的IP地址

**Comment by huxim** [comment]
下面2个已经是cow内置可直连的网站,所以你即使写在block里依然会直连
btw,你的格式是正确的

**Comment by ShinoharaYuri** [comment]
@huxim 
嗯……
這三個網址~ 如果是單獨存在的話~
都會顯示代理IP
但是變成2個及以上的時候就會顯示原本的IP

**Comment by huxim** [comment]
之前的说错了,我刚测试了一下,加入这3个网站后会显示成代理的ip,你是不是使用了pac?直接指定cow的端口试试

**Comment by ShinoharaYuri** [comment]
@huxim 
我這邊也測試成功了……
大概因為回家的原因？這邊ISP是電信……
但是在之前住的地方 ISP是聯通 測試了3天還是我之前遇到的問題……
