### ISSUE TITLE
CentOS6.4安装并配置好cow后该如何启动？

### ISSUE THREAD

**Issue by lwabish** [cyfdecyf/cow#401]
安装完ssh里提示说运行cow &，但是运行后返回一个数字并且报错说command not found。
我看有个linux启动脚本，但是不清楚里面的参数如何更改，以及脚本如何启动？
求指点，多谢！

**Comment by NKUCodingCat** [comment]
./cow &

**Comment by gurtyo** [comment]
在ssh下返回如下

[root@CentOS ~]# ./cow &
[1] 55579
ELF binary type "0" not known.
[root@CentOS ~]# -bash: ./cow: cannot execute binary file

**Comment by gurtyo** [comment]
换到别的vps上试了下可以启动。这个报错的是在freenas的jail里的centos6.4，估计是这个系统的问题，多谢指点

**Comment by NKUCodingCat** [comment]
我觉得第一次应该没问题……但是第二次是被占用了端口无法启动
看看后台有没有在运行就好……说实话我还是觉得在运行的地方编译比较靠谱嗯……

**Comment by gurtyo** [comment]
cow &  返回的是一个pid加command not found
./cow & 返回的就是上面那个无法执行二进制文件的错误了。
我没系统学过linux，不知道加不加./有啥区别。
还有其实这个报错的主机cpu是amd的，或许跟这个有关系？

**Comment by NKUCodingCat** [comment]
加./就是当前目录下的可执行文件啦……所以就是要加./的……
和win下不大一样……要不你试试在那上面装Go然后编译一次【linux就是蛋疼】

**Comment by NKUCodingCat** [comment]
http://www.getnas.com/2015/02/811.html 似乎确实有可能是系统坑……话说为啥不装双系统呢

**Comment by gurtyo** [comment]
以前Windows Server2012+hyperv用着，最近试试freenas，这不刚开始试着用下freenas的jail里的系统。

**Comment by NKUCodingCat** [comment]
=.=噫双系统大法好
![546243595 chatroom_1450075434508_34](https://cloud.githubusercontent.com/assets/8611032/11786166/240a8d90-a2c0-11e5-8029-7de9943f1049.png)

**Comment by gurtyo** [comment]
黑苹果用户？我刚刚入手了第一台白苹果，告别黑苹果了。现在入了折腾NAS的坑了，想着试试exsi多系统呢

**Comment by NKUCodingCat** [comment]
闲得蛋疼多装了俩…以及壕你好~

**Comment by ondreji** [comment]
折腾gen8，痛苦中

**Comment by gurtyo** [comment]
前几天刚德淘gen8下单

**Comment by NKUCodingCat** [comment]
围观壕们晒装备

**Comment by renzhn** [comment]
gen8可以当的x86 PC使，没什么难折腾的。个人装了黑群晖足够用

**Comment by delili** [comment]
求问：./cow  启动cow之后，其他机器上怎么访问这台机器呢？ 代理ip和端口连接cow显示拒绝连接～
