### ISSUE TITLE
公网映射下的服务器pac代理地址不正确

### ISSUE THREAD

**Issue by sanwv** [cyfdecyf/cow#402]
服务器只有局域网ip如192.168.1.123 服务器前面有路由器做映射,例如公网ip是123.123.123.123那访问这个ip的时候路由器会转发给192.168.1.123,服务器对外访问的时候也是通过这个公网ip来走
我配置
```
listen = http://0.0.0.0:7777
```
访问 `http://123.123.123.123:7777/pac` 下载下来的文件显示代理地址是192.168.1.123,显示无法连接.有什么办法手动指定pac的代理地址为公网的ip吗?

**Comment by billryan** [comment]
直接指定，你的写法有误，配置文档里有说。
```
listen = http://127.0.0.1:7777 1.2.3.4:5678
```

**Comment by sanwv** [comment]
内网主机的ip是192.168.1.100 映射的公网ip是1.2.3.100那写成
```
listen = http://1.2.3.100:7777 192.168.1.100:7777
```
那cow就监听在192.168.1.100:7777上但pac的代理地址是1.2.3.100:7777吗?

还是说同时监听在1.2.3.100:777 和192.168.1.100:7777上?(内网主机没有1.2.3.100这个ip网卡呀,并且端口是一一对应的,同时两个ip写同样的端口不会有问题?)

**Comment by billryan** [comment]
这个是 NAT 相关的问题，你想啊，公网 IP 是在路由器上，你本机自然只能监听 192.168.1.100, 然后由于外网访问时只能访问公网，所以你应该写成：
```
listen = http://192.168.1.100:7777 1.2.3.100:7777
```
两个 IP 两个端口这是两个独立的东西，端口与接口绑定，你在路由器上映射什么端口就用什么端口，与本地监听端口无关

**Comment by sanwv** [comment]
确实这样写能正确输出pac,多谢
