### ISSUE TITLE
所有https网站都无法连接

### ISSUE THREAD

**Issue by waymen** [cyfdecyf/cow#404]
0.9.6版 http正常，chrome和firefox都试过
连接https会出现这种错误
parse request malformed request line: "\x16\x03\x01\x00\xa2\x01\x00\x00\x9e\x03\x01\b\u007f\x10\x0e\xdd5\xa7S\x05\xeb\x1d\xe9_\x00\x
1a\x97T>\\[\xf65\xba+\x8c%\x98\x8e\x9a\x11\xcf\f\x00\x00\x14\xc0\n"

**Comment by tlightsky** [comment]
同样问题，怎么解决
