### ISSUE TITLE
我这里centos下使用脚本安装不了，git下来执行安装脚本也不行了

### ISSUE THREAD

**Issue by turing-king** [cyfdecyf/cow#414]
[root@81a0d64db8d4 ~]# curl -L git.io/cow | bash                   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100   285  100   285    0     0     63      0  0:00:04  0:00:04 --:--:--     0
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'

**Comment by NKUCodingCat** [comment]
你这是网有问题吧= =

**Comment by turing-king** [comment]
@NKUCodingCat  不会啊，额 下午自己好了 。 可能和运营商有关系吧，上午bing也打不开
