### ISSUE TITLE
为何我是用二级代理没有效果呢

### ISSUE THREAD

**Issue by turing-king** [cyfdecyf/cow#416]
如下
proxy = ss://aes-256-cfb:123456@xx.xx.xx.xx:1080

当我本机单独使shadowsocks ，并设置 proxy = socks5://127.0.0.1:1080  此时代理正常，
如果使用cow集成的ss二级代理 则没效果
特来求助下

**Comment by turing-king** [comment]
好奇葩，如果直接使用pac是可以的，直接使用代理的端口就不行 
= =

**Comment by turing-king** [comment]
还有就是 我在本机虚拟机centos里使用cow，也是使用的ss，结果没墙的可以访问，墙的还是墙

**Comment by wsxy162** [comment]
proxy = ss://aes-256-cfb:123456@xx.xx.xx.xx:1080
你的ss服务器端口也是1080？

**Comment by turing-king** [comment]
Sorry，一时大意～
