### ISSUE TITLE
负载均衡策略选`latency`后无法上网

### ISSUE THREAD

**Issue by dozer47528** [cyfdecyf/cow#435]
我有2台server

选`backup`可以，但是选`latency`就不行了。

网页打不开，`debug`模式看日志，没有报错。

**Comment by dozer47528** [comment]
找到大概原因了：

我配置了2台速度差不多的服务器，所以每次测速的时候，一会儿可能是A快，一会儿可能就是B快了。

`func (pp *latencyParentPool) updateLatency()`

然后这个方法内部会去测速+排序：

只要顺序一变，就没办法用了。


最快重现方法：

1. 配置2台 shadowsocks server
2. `updateLatency` 方法里不要测速了，直接把速度写死，并且每次调用都要交换
3. 问题重现

**Comment by dozer47528** [comment]
更深层次的原因我还在排查中，毕竟代码不是我自己写的，我也不会 go，所以排查起来会慢一点。

**Comment by atlasliu** [comment]
我试了一下这个latency模式好像只有第一个服务器工作呀。还有这里的latency 指的是到每一个网页的延时吗？

**Comment by dozer47528** [comment]
@atlasliu 
不是，它有个后台线程ping多台服务器，然后选最快的。而不是根据每一个网页的延时。

**Comment by atlasliu** [comment]
也就是说延时是cow服务器到远程代理服务器的延时被？
但是也不太对呀，我ip地址显示的永远都是第一个代理服务器的地址。。。
