### ISSUE TITLE
armv7l binary doesn't run on armv7l hardware

### ISSUE THREAD

**Issue by vbauerster** [cyfdecyf/cow#438]
I wasn't able to run the cow binary on my ASUS RT-AC56U wireless router.
The router is running on [Tomato by Shibby](http://tomato.groov.pl/) firmware.
Following is the error I got:

```
root@zenhub:/opt/tmp/cow# uname -m
armv7l
root@zenhub:/opt/tmp/cow# ./cow-linux-armv7l-0.9.6
runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
```

Is there any workaround?

**Comment by rampageX** [comment]
use arm5t

**Comment by vbauerster** [comment]
Well I tried the arm5t version straight away, but it didn't run for me at all.

**Comment by vbauerster** [comment]
Whew I run arm5t version, I got following:
```
root@zenhub:/opt/tmp/cow# ./cow-linux-armv5tel-0.9.6
Illegal instruction
root@zenhub:/opt/tmp/cow#
```

**Comment by vlbauer** [comment]
Maybe following log, from my wi-fi box, would help to troubleshoot the problem.
```
zenhub kern.notice kernel: Linux version 2.6.36.4brcmarm (shibby@wishmaker) (gcc version 4.5.3 (Buildroot 2012.02) ) #3 SMP PREEMPT Mon Apr 11 15:42:05 CEST 2016
zenhub kern.warn kernel: CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=10c53c7f
zenhub kern.warn kernel: CPU: VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
```

**Comment by rampageX** [comment]
@vlbauer 
native compile on asus ac68u, tested on ac68u/ac56u/r6300v2:

    ./cow -rc ./rc
    2016/04/30 13:18:38 COW 0.9.6 listen http 127.0.0.1:7777, PAC url http://127.0.0.1:7777/pac

https://mega.nz/#!CQxTwbqB!RUOv9oWLvAg9WiUYJwgPZaNq2cj-o0ApER2IqFOiJhY

**Comment by vlbauer** [comment]
Thank you very muck! It works!
