### ISSUE TITLE
微信朋友圈里的图片等都无法显示

### ISSUE THREAD

**Issue by breath-co2** [cyfdecyf/cow#439]
从上周开始，使用cow后，微信朋友圈的所有图片都无法显示，关闭后就能显示，求解决

**Comment by sunshineplan** [comment]
自从上次微信升级后，我也遇到这个情况，不过我觉得应该是微信的问题，ios版有此问题，android版没有

[ERROR] 2016/04/30 18:44:19 can't connect to shadowsocks parent xxxxxxxx:xxxx for [[::ffff:58.211.85.30]]:80: shadowsocks: address error [[::ffff:58.211.85.30]]:80 missing port in address [[::ffff:58.211.85.30]]:80

**Comment by breath-co2** [comment]
@sunshineplan 看了下log确实也是类似这样的错误输出，这个绝对不是微信的问题，我觉得可能微信用了些类似 httpdns 这样的协议，然后cow不支持导致的，希望能尽快解决

**Comment by malagebidi** [comment]
请问下，怎么应用这个patch
