### ISSUE TITLE
0.9.7 Ubuntu下  被Connection Reset的网站并不会转到Proxy去请求直接返回错误

### ISSUE THREAD

**Issue by kiolygenius** [cyfdecyf/cow#445]
http://www.voachinese.com 直接返回Connection Reset, using direct connect

亲测0.9.6不会有这个bug

**Comment by koyabr** [comment]
mac下同样确认0.9.7有此BUG，0.9.6正常

**Comment by loveproe** [comment]
windows下同样的bug不会用代理而直接direct connect！0.9.6版本正常！
