### ISSUE TITLE
how to stop cow-hide?

### ISSUE THREAD

**Issue by rantaolovemm** [cyfdecyf/cow#453]
请教一下，如何停止cow在后台模式？
修改了配置文件后，没办法重新加载。。。
p.s.没试过重启，不觉得重启是个方案。。。

**Comment by DrayChou** [comment]
建议用 cow-taskbar 的这个（单词好像拼错了。

这个修改配置后，可以在图标上点右键重新加载配置。

rantaolovemm <notifications@github.com> 於 2016年5月27日週五 16:12 寫道：

**Comment by rantaolovemm** [comment]
@DrayChow 我用的是Cow hide. 启动了以后taskbar就不能启动啦 所以没办法重新加载

**Comment by huxim** [comment]
自己写个脚本结束进程重开不就好了
