### ISSUE TITLE
One Time Auth开启后,特定请求失败

### ISSUE THREAD

**Issue by defia** [cyfdecyf/cow#461]
大量cli (x.x.x.x:x) send request body error short write POST x.x.x.x.com:8080报错

```
func main() {
	uri, _ := url.Parse("http://127.0.0.1:18080")
	http.ProxyURL(uri)
	http.PostForm("http://www.test.com/", url.Values{"a": {"b"}})
}
```
这个简单的代码就可以验证该问题,且shadowsocks-go无此问题.

**Comment by defia** [comment]
see https://github.com/cyfdecyf/cow/pull/462

**Comment by cyfdecyf** [comment]
谢谢 pr。看来是有某个 Write 的实现没有遵照 `io.Writer` 接口的[约定](https://golang.org/pkg/io/#Writer)

> Write must return a non-nil error if it returns n < len(p).

我想找到这个有问题的 `Write` 实现来修复。

**Comment by defia** [comment]
谢谢回复,了解了

**Comment by cyfdecyf** [comment]
问题出在 shadowsocks 的实现里，已经[修复](https://github.com/shadowsocks/shadowsocks-go/commit/932ea6a5aebb6dd766f7080e01254a2b509e7684)。

这几天用下来没问题的话周末发个新版吧。
