### ISSUE TITLE
macOS 10.12 Public Beta 无法使用

### ISSUE THREAD

**Issue by dozer47528** [cyfdecyf/cow#472]
打开后偶尔可以打开一下，但是后面就无法使用了。
同样的配置，我记得升级前还是可以用的。

**Comment by smallzhan** [comment]
是 go 的问题，我也是一样，升级了 go 1.7 rc1 版, 重编译了一下就好，貌似 1.6 版本有问题。最近他们修改的有一个关于 10.12 beta 的。

**Comment by dozer47528** [comment]
@smallzhan 
我也怀疑 go 的问题，因为我电脑上所有 go 写的程序都有问题

**Comment by nantingshi** [comment]
安装的时候，提示以下错误：
➜  ~ sudo go get github.com/cyfdecyf/cow
package github.com/cyfdecyf/cow: cannot download, $GOPATH not set. For more details see: go help gopath
➜  ~ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/go/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4l/sf7kk_n55kl7h8wtsvhv76vc0000gn/T/go-build993974137=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

操作系统版本是：macOS Sierra beta 2

**Comment by bigtan** [comment]
@nantingshi 没有设置环境变量导致的。

**Comment by nantingshi** [comment]
@bigtan 
最后我使用如下的方式，就顺利安装完成了，然后在10.12 beta系统中正常使用了。

sudo env GOPATH=/usr/local/go/work go get github.com/cyfdecyf/cow
sudo env GOPATH=/usr/local/go/work go install github.com/cyfdecyf/cow

**Comment by dozer47528** [comment]
我用 go1.7 rc3 编译，就可以用了

**Comment by dozer47528** [comment]
我用 go1.7 rc3 编译，就可以用了
