### ISSUE TITLE
无法连接SS的服务器

### ISSUE THREAD

**Issue by today4king** [cyfdecyf/cow#473]
购买了SS的服务，用SS的客户端是可以连接的，但是用COW就不行，奇了怪了。
可以联系下SS为什么么？

**Comment by huiwei19** [comment]
[ERROR] 2016/07/12 19:47:51 estimateTimeout: can't connect to example.com: dial tcp 93.184.216.34:80: getsockopt: connection timed out, network has problem?
我也有同样的问题

**Comment by today4king** [comment]
但是自己搭建的ss服务是可以正常连接的。

**Comment by yyysuo** [comment]
有同样的报错，但是并没有影响翻墙，还是可以上的。
