### ISSUE TITLE
COW怎么支持SS的 -A选项？

### ISSUE THREAD

**Issue by cuminlo** [cyfdecyf/cow#496]
SS的一次性认证听说是能阻止什么攻击，我在服务器上开启之后，本机COW的SS代理就挂了。
那么如何才能在COW支持SS的-A选项呢？

**Comment by bigtan** [comment]
`chacha20-auth` 在加密后面加`-auth`就行

**Comment by cuminlo** [comment]
@bigtan 成功解决，感谢！这个选项是从哪里找到的呀？

**Comment by qiyulan** [comment]
https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc#L71-L76

**Comment by cuminlo** [comment]
@qiyulan 谢谢，我没仔细看。
