### ISSUE TITLE
公司局域网已经提供了一份 Pac 文件作为广域网的出口，该怎么设置 Cow 的 Pac？

### ISSUE THREAD

**Issue by red3** [cyfdecyf/cow#500]
如题，
公司访问外网只能通过公司提供的 Pac，这个 Pac 里面有设置公司内网是 Direct 的，然后其他网段走 Proxy. 但是公司提供的 Proxy 不能翻出去，所以我想在公司的 Proxy 基础套二级代理，通过 ss 来翻出去！

该如何设置呢？

**Comment by yjd** [comment]
直连配到direct.txt
再把你们公司的代理配置到如ssr客户端的二级前置代理上。
浏览器-->cow-->ssr客户端（配置前置代理）-->公司代理-->外网

**Comment by red3** [comment]
@yjd 多谢解惑，现在思路大致是屡清楚了。
ssr Windows 版本是支持直接设置前置代理的，但是 ssr 好像目前没有合适的 Mac 版本；
ss 在 Mac 上无法直接设置前置代理，我的理解是可以使用 Proxifier 或者 ProxyCap 等软件把 ss 的流量中转到公司代理上.

还有两点问题：
1. cow 是否可以根据 direct.txt 走直连，然后其他网站走 公司代理，然后被墙网站走 ss？不然国内网站都走 ss 代理绕一圈就慢了。
2. cow 和 ss 都是通过 pac 来生效，有没有什么兼容办法？

再次感谢！

**Comment by yjd** [comment]
1，你浏览器-->cow，cow就是干这事的。能直连的他就直连了。访问不了才尝试走ss网络。
      cow的blocked.txt和direct.txt。就是让你手动配置。对于一些误判的网站。
2，cow有内置一个pac可以用。也没必要cow和ss两层都判断pac浪费时间。
      本来cow就是智能判断并记忆状态，解决pac列表一大堆网址这种耗时的判断。我都不用pac。

**Comment by red3** [comment]
Hi, 关于第一点可能我没有表述清楚：

> 浏览器-->cow，cow就是干这事的。能直连的他就直连了。

cow 判断出国内常见的网站应该是直连的，流量会是：
浏览器 --> cow --> DIRECT
但是，这里有一个问题是直连是不通的，因为要通过公司提供的代理出口才能到外网，所以流量应该是：
浏览器 --> cow --> Proxy(公司代理) --> 外网

该怎么设置让 cow 里面判断以往直连的，现在走公司的 Proxy？
感谢！

**Comment by yjd** [comment]
我是看你上面说打算用 Proxifier 去让ss走代理。

设置cow的代理策略:

> loadBalance = backup
> proxy = http://xx:1080 /公司代理
> proxy = ss://chacha20:123@ss服务器ip:端口

主用公司代理，遇到墙的网站连不了cow会用第二个去连。
ss的网络连接会被Proxifier劫持走你设置的公司代理，你试试。

**Comment by red3** [comment]
原来可以这样配置！

这样的话，cow 判断出应该直连的时候发现不通，然后会尝试 第一个 proxy，也就是公司的代理。

多谢解惑，我试试！
