### ISSUE TITLE
宽带运营商已经屏蔽github的情况下，如何在线安装？

### ISSUE THREAD

**Issue by gucong3000** [cyfdecyf/cow#501]
如题，我所使用的狗屁宽带，运营商把github屏蔽了，导致安装cow巨麻烦，求解。能否在安装时指定代理服务器？

**Comment by WingGao** [comment]
https://curl.haxx.se/docs/manual.html 文档

``` bash
curl -u user:passwd -x my-proxy:888 -L git.io/cow | bash
```

**Comment by gucong3000** [comment]
@cyfdecyf 能否在安装脚本中添加`-u`, `-x`这俩参数的支持，以便真正实现通过代理安装或升级cow

**Comment by netheril96** [comment]
直接在bash里export环境变量ALL_PROXY再执行安装指令就行了。
