### ISSUE TITLE
内网地址怎么加入direct？

### ISSUE THREAD

**Issue by luboq** [cyfdecyf/cow#512]
比如本机IP 172.16.9.30，目标网站是http://172.16.9.35:6688/
浏览器代理设为cow
即使在direct里写上内网地址，172.16.9.35，也依然不能正常访问
去掉cow，则正常

**Comment by fgggid** [comment]
The website's port is not standard, I think you should add "6688" to "[tunnelAllowedPort](https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc#L139)" in config file.

**Comment by luboq** [comment]
@fgggid 谢谢。我给tunnelAllowedPort加了6688，如图。但依然不能连上；去掉cow代理后，则正常。不知道为什么
连接的网页，是这个app：[WhatsInput，WIFI 无线键盘 - Google Play 上的 Andr​​oid 应用](https://play.google.com/store/apps/details?id=com.buscode.whatsinput&hl=zh)

![gif](http://ooo.0o0.ooo/2016/10/16/580309e7a4155.gif)

**Comment by NKUCodingCat** [comment]
我觉得改了配置是不是就要重启一下……

**Comment by luboq** [comment]
@NKUCodingCat 谢谢，重启cow肯定会的啦，常识。兄台如果说的重启机器，我等会试下…

**Comment by fgggid** [comment]
Never use such app, I'm not sure if this is some compatibility issue of COW; Maybe you can try add your local IP range into "no proxy" of the proxy settings of your browser as a work-around, you see by default, it has "localhost, 127.0.0.1";

**Comment by luboq** [comment]
@fgggid 我太笨，竟没看到浏览器有"no proxy"的配置，加进去，立即解决了。谢谢兄弟！
