### ISSUE TITLE
Cow的server端与shadowsocks-go是一样的吗？

### ISSUE THREAD

**Issue by azgh** [cyfdecyf/cow#519]
cow支持shadowscoks，并且是用go写的，与shadowsocks-go的作者是同一人，那么是不是cow搭建的服务端与shadowsocks-go基本上是一样的？如果不是，有什么区别？
@cyfdecyf 是否考虑将shadowsocks-go和cow合并？

**Comment by DrayChou** [comment]
并不是同一个类型的东西。

cow 支持 shadowsocks ，也支持 http, socks 等代理。
cow 可以认为是 shadwosocks 的一种客户端。

**Comment by azgh** [comment]
@DrayChou 谢谢。
