### ISSUE TITLE
已经有了2个WEB代理,怎么使用COW判断国内走代理1,其它走代理2?

### ISSUE THREAD

**Issue by tywg001** [cyfdecyf/cow#527]
我现在有两个代理,现在环境是只能使用这两个代理上网,一个可以国内,一个可以国外,我现在是在用Flora_Pac文件来做判断,但是发现Performance还是很差,试用了COW在一个直连加一个代理的情况下国内的速度很快,但是COW在我有两个代理,而且一个是国内一个是国外的情况下,无法正常运作,我有使用前面Issues里的那个配置参数,设置cow的代理策略:

    loadBalance = backup
    proxy = http://xx:1080 /代理1
    proxy =  http://xx:8080 /代理2
但是我代理如果网站不通返回的是代理的报错页面,所以COW无法判断是否不通,也就无法调用第二个代理来使用,这个场景有办法解决吗?
代理报错如下:
![1](https://cloud.githubusercontent.com/assets/1572723/21669492/1db12216-d347-11e6-81e0-747a0f2da4cc.JPG)

**Comment by DrayChou** [comment]
cow 本身有一套路由检测，如果能联通就不走代理。
你要的这套要求不建议用 cow 来解决。

**Comment by tywg001** [comment]
@DrayChou 嗯,我现在是在用PAC文件做这个对应案,看来也只能这样了,就是响应速度不快
