### ISSUE TITLE
安装指南里的下载速度有点慢

### ISSUE THREAD

**Issue by magicdlf** [cyfdecyf/cow#532]
安装指南给出的安装方式：
curl -L git.io/cow | bash
在阿里云的服务器上执行，下载太慢了。建议可以上传到CDN上面。

**Comment by ZengLeiPro** [comment]
确实非常慢

**Comment by sysserkl** [comment]
没速度。linux 下如何离线安装？

**Comment by sammdu** [comment]
离线安装其实很简单，ubuntu作客户端今天亲测可行; 服务器端大同小异
1.去releases下载跟自己平台相符的gz归档;
2.解压出`cow-<版本>`执行文件，改名为`cow`;
3. `sudo cp ./cow /usr/bin`
4. `sudo chmod +x /usr/bin/cow`
5. `mkdir ~/.cow/`
6. `cp <下载到的样例配置文件，也就是rc> ~/.cow/rc`   
***
第6步不做也行，直接跳到下一步手动输入配置; 具体看readme
***

7 `nano ~/.cow/rc` 用文本编辑器改配置或手动输入配置，我在这里用nano，大神可以用vim/emacs ;-)
8. 现在为止就可以运行`cow &`开启服务器了，它会自动读配置; 我自己其实还配合`screen`命令写了个小脚本方便运行管理，有时间贴出来

建议 @cyfdecyf 把这个放到readme 或 wiki 里 ;-)

**Comment by sammdu** [comment]
还有，欢迎纠错，打的比较仓促，可能手抖 ;-)

**Comment by sammdu** [comment]
@magicdlf @ZengLeiPro @sysserkl 试试可以用的话，就把issue关了哦 ;-)
后台运行的脚本我也传上去了 `>>`
https://gist.github.com/SammDu/72ea27885d8c01036f71e39e871c8b6d
这个脚本主要是方便看错误信息可以直接修复，不用读log之类，直接用`screen`命令切换即可看到。
依赖`screen`程序，所以用之前先

> sudo apt install screen

之后，
`sudo cp ./runcow.sh /usr/bin/`
`sudo chmod +x /usr/bin/runcow.sh`
应该就可以直接运行runcow.sh启动cow了。

**Comment by magicdlf** [comment]
恩是的，需要下载相应的版本。
