### ISSUE TITLE
代理就是代理,不要多事行吗?

### ISSUE THREAD

**Issue by ugksoft** [cyfdecyf/cow#552]
不要多此一举

<!DOCTYPE html>
<html>
	<head> <title>COW Proxy</title> </head>
	<body>
		<h1>[Error] socks protocol error</h1>
		<p>HTTP Request <strong>GET xxxxxxxxxxxxx</strong></p> <p>Parent proxy connection failed, always use parent proxy.</p>
		<hr />
		Generated by <i>COW 0.9.8</i> <br />
		Host <i>xxxxxxxxxx</i> <br />
		Mon Aug 04 11:22:33 2017
	</body>
</html>

如果对方服务器,真的是404的,或是不能访问的(IP不通,或是被墙而不通), 不要返回这种垃圾回应
是什么就是什么, 不然,人脑好判断,但电脑软件(比如一些扫描软件,批处理类软件等),没办法判断这是远程网页返回的实际数据,还是你软件的数据!!!!!!!!!!!!!!!!!!!!

发现Privoxy也有同样的变态问题

**Comment by ugksoft** [comment]
```
被github格式化了,重发html回应内容

HTTP/1.1 504 Connection failed
Connection: keep-alive
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html
Content-Length: 385

<!DOCTYPE html>
<html>
	<head> <title>COW Proxy</title> </head>
	<body>
		<h1>[Error] socks protocol error</h1>
		<p>HTTP Request <strong>GET xxxxxxxxxxx</strong></p> <p>Parent proxy connection failed, always use parent proxy.</p>
		<hr />
		Generated by <i>COW 0.9.8</i> <br />
		Host <i>xxxxxx</i> <br />
		Mon Aug 10 11:22:33 2017
	</body>
</html>

```



标题有点不太客气,但是真的有点事蛇贴足,  sorry

**Comment by childe** [comment]
我相信404, 包括服务器直接返回的504, cow都会直接返回给你的.
但如果真的超时呢, 你难道愿意一直等下去?
个人见解, 要回复的话请对我客气点.

**Comment by qiuyi21** [comment]
@ugksoft 你不满意可以自己修改代码帮忙开发，别人开发还免费使用你还不知足，注意素质。

**Comment by ugksoft** [comment]
如果真的超时了,那直接断掉本次连接就是了,不应该回复替代内容,这样一些扫描软件,抓网站的软件等,还以为页面不存在或是服务器出错等,跳过这连接,不报错

**Comment by childe** [comment]
@ugksoft 可能是你的软件太SB了, 或者是你自己太SB.

**Comment by ugksoft** [comment]
楼上你什么态度, 几乎99%的软件是不会考虑代理问题的,是不支持的, 在这1%里的99%,代理也只是勉强支持的,你还能指望剩下的,能够完美的处理代理错误? 幼稚!

另外,作者可能Windows编程经验=0,所以,托盘程序都要单独写一个,弹出界面上,什么都不显示, 都写了Win32程序了,界面上,随便折腾一下,写个配置,或是其它的, 几分种的事情,居然也不干



另外,关了这贴子吧,我也懒的来回复
