### ISSUE TITLE
osx 10.13.1 不能运行

### ISSUE THREAD

**Issue by coolicer** [cyfdecyf/cow#556]
failed MSpanList_Insert 0x604000 0xa881611170 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x320e30, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff670 sp=0x7ffeefbff658
runtime.(*mSpanList).insert(0x46c5c8, 0x604000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff6a0 sp=0x7ffeefbff670
runtime.(*mheap).freeSpanLocked(0x46bdc0, 0x604000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff708 sp=0x7ffeefbff6a0
runtime.(*mheap).grow(0x46bdc0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff760 sp=0x7ffeefbff708
runtime.(*mheap).allocSpanLocked(0x46bdc0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff7b8 sp=0x7ffeefbff760
runtime.(*mheap).alloc_m(0x46bdc0, 0x1, 0x15, 0x0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff7e8 sp=0x7ffeefbff7b8
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff818 sp=0x7ffeefbff7e8
runtime.systemstack(0x7ffeefbff838)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff820 sp=0x7ffeefbff818
runtime.(*mheap).alloc(0x46bdc0, 0x1, 0x10000000015, 0x5a29f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff868 sp=0x7ffeefbff820
runtime.(*mcentral).grow(0x46d9c0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff8d0 sp=0x7ffeefbff868
runtime.(*mcentral).cacheSpan(0x46d9c0, 0x4679d8)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff910 sp=0x7ffeefbff8d0
runtime.(*mcache).refill(0x600000, 0x15, 0x7ffeefbff978)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff948 sp=0x7ffeefbff910
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff968 sp=0x7ffeefbff948
runtime.systemstack(0x7ffeefbffa08)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff970 sp=0x7ffeefbff968
runtime.mallocgc(0x180, 0x2e8c00, 0x0, 0x800000000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbffa48 sp=0x7ffeefbff970
runtime.newobject(0x2e8c00, 0x468050)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbffa70 sp=0x7ffeefbffa48
runtime.malg(0x8000, 0x4682c0)
	/usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbffaa8 sp=0x7ffeefbffa70
runtime.mpreinit(0x468820)
	/usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbffac0 sp=0x7ffeefbffaa8
runtime.mcommoninit(0x468820)
	/usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbffb08 sp=0x7ffeefbffac0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffb50 sp=0x7ffeefbffb08
runtime.rt0_go(0x7ffeefbffb80, 0x1, 0x7ffeefbffb80, 0x0, 0x1, 0x7ffeefbffc98, 0x0, 0x7ffeefbffc9c, 0x7ffeefbffcde, 0x7ffeefbffcec, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffb58 sp=0x7ffeefbffb50

**Comment by kitt1987** [comment]
Rebuild the binary on OSX 10.13.1 can easily fix it.

**Comment by mgttt** [comment]
any one help to build one?

**Comment by kitt1987** [comment]
@wanjochan The size of the compressed binary is about 1.5MB. I guess I can email it to you.

**Comment by mgttt** [comment]
@kitt1987 I've the same ID of wechat(wanjochan), will you add me friend :)

**Comment by lidaling** [comment]
```
failed MSpanList_Insert 0x604000 0x57856ca464601 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x320e30, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfe900 sp=0x7ffeefbfe8e8
runtime.(*mSpanList).insert(0x46c5c8, 0x604000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbfe930 sp=0x7ffeefbfe900
runtime.(*mheap).freeSpanLocked(0x46bdc0, 0x604000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbfe998 sp=0x7ffeefbfe930
runtime.(*mheap).grow(0x46bdc0, 0x8, 0x0)
```

But there is no dir named `	/usr/local/go/src`

**Comment by mgttt** [comment]
@lidaling   https://github.com/wanjochan/cow/releases/tag/0.9.8mac  it's from share of @kitt1987 /cheers
