### ISSUE TITLE
配置代码不好读，为什么不用viper包，读取toml格式的配置来做呢

### ISSUE THREAD

**Issue by wpecker** [cyfdecyf/cow#563]
用反射好奇怪，代码不好读；还是toml格式最好; txt做配置太奇葩了

**Comment by cyfdecyf** [comment]
cow 的第一个 commit 比 viper 早两年。

**Comment by wpecker** [comment]
@cyfdecyf ， 原来是这个原因呵， 花点时间改成viper吧，我想也花不了多少时间，因为代码你都懂，否则没办法贡献代码，反射txt文本。
