### ISSUE TITLE
blocked 文件没有生效

### ISSUE THREAD

**Issue by chrisyip** [cyfdecyf/cow#96]
我分别在 `~/.cow/blocked` 和 `~/.cow/direct` 中添加规则，但在 pac 里只更新了 `direct` 的规则，看上去 `blocked` 是被忽略了。

尝试性地加了 `ip.cn` 到 `blocked`，检测出来的 IP 仍然是国内的。

安装的版本是从 go 源码编译安装的。

**Comment by kingwrcy** [comment]
我也是一样的问题,找到原因了,pac被浏览器缓存了,去网络设置里去掉pac的代理,确定完之后再填写一次pac的地址,缓存就没了.
